### ISSUE TITLE
PHP Fatal error:  Trait 'Watson\Validating\ValidatingTrait' not found

### ISSUE THREAD

**Issue by ayoolatj** [rinvex/laravel-support#19]
I get an error when using the rinvex/addresses package

 Symfony\Component\Debug\Exception\FatalErrorException  : Trait 'Watson\Validating\ValidatingTrait' not found

**Comment by Omranic** [comment]
This is already fixed on `develop` branch 7594fb76209ab9562514c28dd9a1316d45b4d88a
