### ISSUE TITLE
Wrong locale 

### ISSUE THREAD

**Issue by afshiney** [rinvex/laravel-support#56]
Hey there, 
I've encountered an issue that originally happened upon installing [laravel-categories](https://github.com/rinvex/laravel-categories) package, 

When installed, application locale would switch to default "en" and not respond as correct set locale,
I tracked down and realized this package as a dependecy for [laravel-categories](https://github.com/rinvex/laravel-categories) is causing the issue and even when installing it separately as the main root dependency it causes the same issue.

Update: tracked down the issue to be actually initiating from [uniquewith-validator](https://github.com/felixkiss/uniquewith-validator)

**Comment by Omranic** [comment]
Hope it's all sorted, please let me know if I can help.
