### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by Pilskalns** [rinvex/laravel-support#64]
Hi,

This package is dependent on `rinvex/tmp-watson-validating ^6.0.0` which in turn depends on `illuminate/validation ^8.0`  thus breaking the dependency chain. To my understanding, the dependencies on validating package should be updated.

The full dependency chain: 
`L9` > `rinvex/laravel-addresses ^6.0` > `rinvex/laravel-support ^6.0.0` > `rinvex/tmp-watson-validating ^6.0.0` > `illuminate/validation ^8.0.0`

P.S. creating issue here since the `tmp-watson-validating` package does not have Issue Tracker enabled.

**Comment by robbielove** [comment]
We don't even need the `tmp-watson-validating` anymore - this fork was originally used because https://github.com/dwightwatson/validating didn't have L8 support.

It now has L9 support so it could just be switched to use that and problem solved? 🤷‍♂️

**Comment by stephenjude** [comment]
Yeah was trying to add L9 support because of the same issue. What's do you suggest @robbielove

**Comment by Omranic** [comment]
@Pilskalns @stephenjude thanks, L9 support coming this week 👍 

@robbielove awesome, that's good news, will check that and switch it back then 🙌

**Comment by stephenjude** [comment]
Okay

**Comment by stephenjude** [comment]
Thanks @Omranic

**Comment by Omranic** [comment]
Laravel v9 is now supported in latest release v6.1.0, also all of our packages now supports Laravel v9.

## Note when using this package with Laravel v9

This package requires `felixkiss/uniquewith-validator` dependency, which is not yet compatible with Laravel v9! However as a temporary workaround, add [Laravel Shift](https://github.com/felixkiss/uniquewith-validator/pull/131)'s fork to the `repositories` property of your project root `composer.json`:
```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/uniquewith-validator.git"
        }
    ]
}
```

**Comment by azenot-dev** [comment]
> Laravel v9 is now supported in latest release v6.1.0, also all of our packages now supports Laravel v9.
> 
> ## Note when using this package with Laravel v9
> This package requires `felixkiss/uniquewith-validator` dependency, which is not yet compatible with Laravel v9! However as a temporary workaround, add [Laravel Shift](https://github.com/felixkiss/uniquewith-validator/pull/131)'s fork to the `repositories` property of your project root `composer.json`:
> 
> ```json
> {
>     "repositories": [
>         {
>             "type": "vcs",
>             "url": "https://github.com/laravel-shift/uniquewith-validator.git"
>         }
>     ]
> }
> ```

I get this error
GitHub API limit (0 calls/hr) is exhausted, could not fetch https://api.github.com/repos/laravel-shift/uniquewith-validator/commits/ad94e9b14bca5e7afd9a578c023fe3937d6bcdaa. Create a GitHub OAuth token to go over the API rate limit. You can also wait until ? for the rate limit to reset.

**Comment by Omranic** [comment]
@azenot-dev https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens

**Comment by Omranic** [comment]
Update: we dropped the `felixkiss/uniquewith-validator` dependency from this package 🙂 https://github.com/rinvex/laravel-support/commit/2bf69b8dcbf6f18ecd97c2c7b43ae441d58765cd

**Comment by robbielove** [comment]
Thanks for that
