### ISSUE TITLE
Update the `dwightwatson/validating` dependency to allow Illuminate 10 compatibility

### ISSUE THREAD

**Issue by andrecolza** [rinvex/laravel-support#71]
Version 7 of `dwightwatson/validating` requires Illuminate "~8.0|~9.0", please update it to version 8 to allow compatibility with Illuminate 10.

**Comment by forxer** [comment]
please @Omranic  could you merge PR here and in https://github.com/rinvex/laravel-categories that way users can continue using these packages

or if you wish to give them up mark it clearly as being so that we can determine a strategy

**Comment by Omranic** [comment]
Hey @forxer thanks for the heads-up, yeah need to update this. Let me look into this and other affected packages. Stay tuned..

**Comment by Omranic** [comment]
Fixed here https://github.com/rinvex/laravel-support/commit/e97387da7c41e47f135f5e809ed83068e2ca5566
